# Generated by Django 2.2.9 on 2020-04-04 18:38

from django.db import migrations, models
import tenant.models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(editable=False, max_length=128, unique=True)),
                ('schema_name', models.CharField(editable=False, max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, unique=True, validators=[tenant.models.check_tenant_name])),
                ('desc', models.TextField(blank=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
